package com.enhanced;

// IMPORTS
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

import com.enhanced.block.CustomSlab;

// CLASS
public class Enhanced implements ModInitializer {

  // PROPERTIES
  public static final String MOD_ID = "enhanced";

  // BLOCKS
  public static final Block OAK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
  public static final Block BIRCH_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.BIRCH_SLAB));
  public static final Block SPRUCE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.SPRUCE_SLAB));
  public static final Block JUNGLE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.JUNGLE_SLAB));
  public static final Block ACACIA_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.ACACIA_SLAB));
  public static final Block DARK_OAK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.DARK_OAK_SLAB));
  public static final Block MANGROVE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.MANGROVE_SLAB));
  public static final Block CHERRY_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.CHERRY_SLAB));
  public static final Block BAMBOO_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.BAMBOO_SLAB));
  public static final Block BAMBOO_MOSAIC_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.BAMBOO_MOSAIC_SLAB));
  public static final Block CRIMSON_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.CRIMSON_SLAB));
  public static final Block WARPED_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.WARPED_SLAB));
  public static final Block STONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.STONE_SLAB));
  public static final Block COBBLESTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.COBBLESTONE_SLAB));
  public static final Block MOSSY_COBBLESTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.MOSSY_COBBLESTONE_SLAB));
  public static final Block SMOOTH_STONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.SMOOTH_STONE_SLAB));
  public static final Block STONE_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.STONE_BRICK_SLAB));
  public static final Block MOSSY_STONE_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.MOSSY_STONE_BRICK_SLAB));
  public static final Block COBBLED_DEEPSLATE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE_SLAB));
  public static final Block POLISHED_DEEPSLATE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.POLISHED_DEEPSLATE_SLAB));
  public static final Block DEEPSLATE_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.DEEPSLATE_BRICK_SLAB));
  public static final Block DEEPSLATE_TILE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.DEEPSLATE_TILE_SLAB));
  public static final Block GRANITE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.GRANITE_SLAB));
  public static final Block POLISHED_GRANITE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.POLISHED_GRANITE_SLAB));
  public static final Block DIORITE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.DIORITE_SLAB));
  public static final Block POLISHED_DIORITE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.POLISHED_DIORITE_SLAB));
  public static final Block ANDESITE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.ANDESITE_SLAB));
  public static final Block POLISHED_ANDESITE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.POLISHED_ANDESITE_SLAB));
  public static final Block BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.BRICK_SLAB));
  public static final Block MUD_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.MUD_BRICK_SLAB));
  public static final Block SANDSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.SANDSTONE_SLAB));
  public static final Block SMOOTH_SANDSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.SMOOTH_SANDSTONE_SLAB));
  public static final Block CUT_SANDSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.CUT_SANDSTONE_SLAB));
  public static final Block RED_SANDSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE_SLAB));
  public static final Block SMOOTH_RED_SANDSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.SMOOTH_RED_SANDSTONE_SLAB));
  public static final Block CUT_RED_SANDSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.CUT_RED_SANDSTONE_SLAB));
  public static final Block PRISMARINE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.PRISMARINE_SLAB));
  public static final Block PRISMARINE_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.PRISMARINE_BRICK_SLAB));
  public static final Block DARK_PRISMARINE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.DARK_PRISMARINE_SLAB));
  public static final Block NETHER_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.NETHER_BRICK_SLAB));
  public static final Block RED_NETHER_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.RED_NETHER_BRICK_SLAB));
  public static final Block BLACKSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.BLACKSTONE_SLAB));
  public static final Block POLISHED_BLACKSTONE_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.POLISHED_BLACKSTONE_SLAB));
  public static final Block POLISHED_BLACKSTONE_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB));
  public static final Block END_STONE_BRICK_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.END_STONE_BRICK_SLAB));
  public static final Block PURPUR_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.PURPUR_SLAB));
  public static final Block QUARTZ_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.QUARTZ_SLAB));
  public static final Block SMOOTH_QUARTZ_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.SMOOTH_QUARTZ_SLAB));
  public static final Block CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.CUT_COPPER_SLAB));
  public static final Block EXPOSED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.EXPOSED_CUT_COPPER_SLAB));
  public static final Block WEATHERED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.WEATHERED_CUT_COPPER_SLAB));
  public static final Block OXIDIZED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.OXIDIZED_CUT_COPPER_SLAB));
  public static final Block WAXED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.WAXED_CUT_COPPER_SLAB));
  public static final Block WAXED_EXPOSED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB));
  public static final Block WAXED_WEATHERED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB));
  public static final Block WAXED_OXIDIZED_CUT_COPPER_SLAB = new CustomSlab(FabricBlockSettings.copyOf(Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB));

  // INITIALIZE
  @Override
  public void onInitialize() {

    ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(content -> {
      content.add(OAK_SLAB);
      content.add(BIRCH_SLAB);
      content.add(SPRUCE_SLAB);
      content.add(JUNGLE_SLAB);
      content.add(ACACIA_SLAB);
      content.add(DARK_OAK_SLAB);
      content.add(MANGROVE_SLAB);
      content.add(CHERRY_SLAB);
      content.add(BAMBOO_SLAB);
      content.add(BAMBOO_MOSAIC_SLAB);
      content.add(CRIMSON_SLAB);
      content.add(WARPED_SLAB);
      content.add(STONE_SLAB);
      content.add(COBBLESTONE_SLAB);
      content.add(MOSSY_COBBLESTONE_SLAB);
      content.add(SMOOTH_STONE_SLAB);
      content.add(STONE_BRICK_SLAB);
      content.add(MOSSY_STONE_BRICK_SLAB);
      content.add(GRANITE_SLAB);
      content.add(POLISHED_GRANITE_SLAB);
      content.add(DIORITE_SLAB);
      content.add(POLISHED_DIORITE_SLAB);
      content.add(ANDESITE_SLAB);
      content.add(POLISHED_ANDESITE_SLAB);
      content.add(COBBLED_DEEPSLATE_SLAB);
      content.add(POLISHED_DEEPSLATE_SLAB);
      content.add(DEEPSLATE_BRICK_SLAB);
      content.add(DEEPSLATE_TILE_SLAB);
      content.add(BRICK_SLAB);
      content.add(MUD_BRICK_SLAB);
      content.add(SANDSTONE_SLAB);
      content.add(SMOOTH_SANDSTONE_SLAB);
      content.add(CUT_SANDSTONE_SLAB);
      content.add(RED_SANDSTONE_SLAB);
      content.add(SMOOTH_RED_SANDSTONE_SLAB);
      content.add(CUT_RED_SANDSTONE_SLAB);
      content.add(PRISMARINE_SLAB);
      content.add(PRISMARINE_BRICK_SLAB);
      content.add(DARK_PRISMARINE_SLAB);
      content.add(NETHER_BRICK_SLAB);
      content.add(RED_NETHER_BRICK_SLAB);
      content.add(BLACKSTONE_SLAB);
      content.add(POLISHED_BLACKSTONE_SLAB);
      content.add(POLISHED_BLACKSTONE_BRICK_SLAB);
      content.add(END_STONE_BRICK_SLAB);
      content.add(PURPUR_SLAB);
      content.add(QUARTZ_SLAB);
      content.add(SMOOTH_QUARTZ_SLAB);
      content.add(CUT_COPPER_SLAB);
      content.add(EXPOSED_CUT_COPPER_SLAB);
      content.add(WEATHERED_CUT_COPPER_SLAB);
      content.add(OXIDIZED_CUT_COPPER_SLAB);
      content.add(WAXED_CUT_COPPER_SLAB);
      content.add(WAXED_EXPOSED_CUT_COPPER_SLAB);
      content.add(WAXED_WEATHERED_CUT_COPPER_SLAB);
      content.add(WAXED_OXIDIZED_CUT_COPPER_SLAB);
    });

    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "oak_slab"), OAK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "birch_slab"), BIRCH_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "spruce_slab"), SPRUCE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "jungle_slab"), JUNGLE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "acacia_slab"), ACACIA_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "dark_oak_slab"), DARK_OAK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "mangrove_slab"), MANGROVE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cherry_slab"), CHERRY_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "bamboo_slab"), BAMBOO_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "bamboo_mosaic_slab"), BAMBOO_MOSAIC_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "crimson_slab"), CRIMSON_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "warped_slab"), WARPED_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "stone_slab"), STONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cobblestone_slab"), COBBLESTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "mossy_cobblestone_slab"), MOSSY_COBBLESTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "smooth_stone_slab"), SMOOTH_STONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "stone_brick_slab"), STONE_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "mossy_stone_brick_slab"), MOSSY_STONE_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "granite_slab"), GRANITE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "polished_granite_slab"), POLISHED_GRANITE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "diorite_slab"), DIORITE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "polished_diorite_slab"), POLISHED_DIORITE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "andesite_slab"), ANDESITE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "polished_andesite_slab"), POLISHED_ANDESITE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cobbled_deepslate_slab"), COBBLED_DEEPSLATE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "polished_deepslate_slab"), POLISHED_DEEPSLATE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "deepslate_brick_slab"), DEEPSLATE_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "deepslate_tile_slab"), DEEPSLATE_TILE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "brick_slab"), BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "mud_brick_slab"), MUD_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "sandstone_slab"), SANDSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "smooth_sandstone_slab"), SMOOTH_SANDSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cut_sandstone_slab"), CUT_SANDSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "red_sandstone_slab"), RED_SANDSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "smooth_red_sandstone_slab"), SMOOTH_RED_SANDSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cut_red_sandstone_slab"), CUT_RED_SANDSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "prismarine_slab"), PRISMARINE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "prismarine_brick_slab"), PRISMARINE_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "dark_prismarine_slab"), DARK_PRISMARINE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "nether_brick_slab"), NETHER_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "red_nether_brick_slab"), RED_NETHER_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "blackstone_slab"), BLACKSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "polished_blackstone_slab"), POLISHED_BLACKSTONE_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "polished_blackstone_brick_slab"), POLISHED_BLACKSTONE_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "end_stone_brick_slab"), END_STONE_BRICK_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "purpur_slab"), PURPUR_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "quartz_slab"), QUARTZ_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "smooth_quartz_slab"), SMOOTH_QUARTZ_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "cut_copper_slab"), CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "exposed_cut_copper_slab"), EXPOSED_CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "weathered_cut_copper_slab"), WEATHERED_CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "oxidized_cut_copper_slab"), OXIDIZED_CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "waxed_cut_copper_slab"), WAXED_CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "waxed_exposed_cut_copper_slab"), WAXED_EXPOSED_CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "waxed_weathered_cut_copper_slab"), WAXED_WEATHERED_CUT_COPPER_SLAB);
    Registry.register(Registries.BLOCK, new Identifier(MOD_ID, "waxed_oxidized_cut_copper_slab"), WAXED_OXIDIZED_CUT_COPPER_SLAB);

    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "oak_slab"), new BlockItem(OAK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "birch_slab"), new BlockItem(BIRCH_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "spruce_slab"), new BlockItem(SPRUCE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "jungle_slab"), new BlockItem(JUNGLE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "acacia_slab"), new BlockItem(ACACIA_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "dark_oak_slab"), new BlockItem(DARK_OAK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "mangrove_slab"), new BlockItem(MANGROVE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "cherry_slab"), new BlockItem(CHERRY_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "bamboo_slab"), new BlockItem(BAMBOO_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "bamboo_mosaic_slab"), new BlockItem(BAMBOO_MOSAIC_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "crimson_slab"), new BlockItem(CRIMSON_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "warped_slab"), new BlockItem(WARPED_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "stone_slab"), new BlockItem(STONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "cobblestone_slab"), new BlockItem(COBBLESTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "mossy_cobblestone_slab"), new BlockItem(MOSSY_COBBLESTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "smooth_stone_slab"), new BlockItem(SMOOTH_STONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "stone_brick_slab"), new BlockItem(STONE_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "mossy_stone_brick_slab"), new BlockItem(MOSSY_STONE_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "granite_slab"), new BlockItem(GRANITE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "polished_granite_slab"), new BlockItem(POLISHED_GRANITE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "diorite_slab"), new BlockItem(DIORITE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "polished_diorite_slab"), new BlockItem(POLISHED_DIORITE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "andesite_slab"), new BlockItem(ANDESITE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "polished_andesite_slab"), new BlockItem(POLISHED_ANDESITE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "cobbled_deepslate_slab"), new BlockItem(COBBLED_DEEPSLATE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "polished_deepslate_slab"), new BlockItem(POLISHED_DEEPSLATE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "deepslate_brick_slab"), new BlockItem(DEEPSLATE_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "deepslate_tile_slab"), new BlockItem(DEEPSLATE_TILE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "brick_slab"), new BlockItem(BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "mud_brick_slab"), new BlockItem(MUD_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "sandstone_slab"), new BlockItem(SANDSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "smooth_sandstone_slab"), new BlockItem(SMOOTH_SANDSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "cut_sandstone_slab"), new BlockItem(CUT_SANDSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "red_sandstone_slab"), new BlockItem(RED_SANDSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "smooth_red_sandstone_slab"), new BlockItem(SMOOTH_RED_SANDSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "cut_red_sandstone_slab"), new BlockItem(CUT_RED_SANDSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "prismarine_slab"), new BlockItem(PRISMARINE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "prismarine_brick_slab"), new BlockItem(PRISMARINE_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "dark_prismarine_slab"), new BlockItem(DARK_PRISMARINE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "nether_brick_slab"), new BlockItem(NETHER_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "red_nether_brick_slab"), new BlockItem(RED_NETHER_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "blackstone_slab"), new BlockItem(BLACKSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "polished_blackstone_slab"), new BlockItem(POLISHED_BLACKSTONE_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "polished_blackstone_brick_slab"), new BlockItem(POLISHED_BLACKSTONE_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "end_stone_brick_slab"), new BlockItem(END_STONE_BRICK_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "purpur_slab"), new BlockItem(PURPUR_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "quartz_slab"), new BlockItem(QUARTZ_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "smooth_quartz_slab"), new BlockItem(SMOOTH_QUARTZ_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "cut_copper_slab"), new BlockItem(CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "exposed_cut_copper_slab"), new BlockItem(EXPOSED_CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "weathered_cut_copper_slab"), new BlockItem(WEATHERED_CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "oxidized_cut_copper_slab"), new BlockItem(OXIDIZED_CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "waxed_cut_copper_slab"), new BlockItem(WAXED_CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "waxed_exposed_cut_copper_slab"), new BlockItem(WAXED_EXPOSED_CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "waxed_weathered_cut_copper_slab"), new BlockItem(WAXED_WEATHERED_CUT_COPPER_SLAB, new Item.Settings()));
    Registry.register(Registries.ITEM, new Identifier(MOD_ID, "waxed_oxidized_cut_copper_slab"), new BlockItem(WAXED_OXIDIZED_CUT_COPPER_SLAB, new Item.Settings()));

  }

}
